/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intrasyspos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ashiq
 */
public class NewTransaction extends javax.swing.JFrame {
    public int row=1;
    public double grandTotal = 0;
    DecimalFormat df = new DecimalFormat("0.00");
    public double taxRate = 0.07; //7%
    public double tax = 0; //in numbers
    public double discount = 0;
    public ArrayList<Long> cart = new ArrayList<Long>();
    public double membershipDiscount = 0;
    public double discAmt = 0;
    public boolean abSet; //check if BuyAGetB has alr been applied
    public double subTotal = 0;
    public Long customerId = -1L;
    public Long transactionID = -1L;

    /**
     * Creates new form NewTransaction
     */
    public NewTransaction() {
        initComponents();
        String timeStamp = new SimpleDateFormat("dd.MM.yyyy    HH.mm.ss").format(new java.util.Date());
        showDate();
        showTime();
        
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        dateLab.setText(s.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeLab.setText(s.format(d));
            }
            
        }).start(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jNewTransactionButton1 = new javax.swing.JButton();
        jRetrieveTransactionButton2 = new javax.swing.JButton();
        jMembershipButton3 = new javax.swing.JButton();
        jPromotionsButton4 = new javax.swing.JButton();
        jProductsButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTransactionTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSearchItemTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jGrandTotalTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTaxTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        dateLab = new javax.swing.JLabel();
        timeLab = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1649, 1104));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jNewTransactionButton1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jNewTransactionButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cart.png"))); // NOI18N
        jNewTransactionButton1.setText("New Transaction");
        jNewTransactionButton1.setMinimumSize(new java.awt.Dimension(100, 100));
        jNewTransactionButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jNewTransactionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewTransactionButton1ActionPerformed(evt);
            }
        });

        jRetrieveTransactionButton2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jRetrieveTransactionButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/oldtransaction.png"))); // NOI18N
        jRetrieveTransactionButton2.setText("Retrieve Transaction");
        jRetrieveTransactionButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jRetrieveTransactionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetrieveTransactionButton2ActionPerformed(evt);
            }
        });

        jMembershipButton3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jMembershipButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Member.png"))); // NOI18N
        jMembershipButton3.setText("Membership");

        jPromotionsButton4.setBackground(new java.awt.Color(0, 0, 0));
        jPromotionsButton4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jPromotionsButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/promotions.png"))); // NOI18N
        jPromotionsButton4.setText("View Promotions");
        jPromotionsButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPromotionsButton4ActionPerformed(evt);
            }
        });

        jProductsButton5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jProductsButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/products.png"))); // NOI18N
        jProductsButton5.setText("View Products");
        jProductsButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductsButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings.png"))); // NOI18N
        jButton2.setText("Settings");
        jButton2.setMargin(new java.awt.Insets(2, -30, 2, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRetrieveTransactionButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNewTransactionButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMembershipButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPromotionsButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProductsButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNewTransactionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRetrieveTransactionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jMembershipButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPromotionsButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProductsButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTransactionTable1.setBackground(new java.awt.Color(222, 228, 222));
        jTransactionTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Item ID", "Name", "Price", "Quantity", "Discount", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTransactionTable1.setRowHeight(50);
        jTransactionTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTransactionTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTransactionTable1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTransactionTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTransactionTable1);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setText("Sales Invoice:#");

        jSearchItemTextField1.setFont(new java.awt.Font("Calibri Light", 2, 20)); // NOI18N
        jSearchItemTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchItemTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jGrandTotalTextField3.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jGrandTotalTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrandTotalTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 40)); // NOI18N
        jLabel2.setText("Grand Total:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel3.setText("Membership Account:");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel6.setText("Tax:");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel7.setText("Vouchers:");

        jTaxTextField3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jTaxTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaxTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N

        jButton4.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/payment.png"))); // NOI18N
        jButton4.setText("Checkout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/saveTranx.png"))); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel5.setText("Scan Item:");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        dateLab.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        dateLab.setText("jLabel8");

        timeLab.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        timeLab.setText("jLabel9");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setText("Date:");

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel9.setText("Time:");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel4.setText("Member Discount:");

        discountField.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel10.setText("Subtotal:");

        subtotal.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jTextField6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jGrandTotalTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTaxTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(616, 616, 616)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSearchItemTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(timeLab)
                                        .addGap(183, 183, 183)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateLab)))
                            .addComponent(jScrollPane1))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSearchItemTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateLab)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeLab)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(230, 230, 230)
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTaxTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jGrandTotalTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewTransactionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewTransactionButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNewTransactionButton1ActionPerformed

    private void jRetrieveTransactionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetrieveTransactionButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRetrieveTransactionButton2ActionPerformed

    private void jProductsButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductsButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProductsButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jGrandTotalTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrandTotalTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGrandTotalTextField3ActionPerformed

    private void jTaxTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaxTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPromotionsButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPromotionsButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPromotionsButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int quantity=1;
        
        String itemId = jSearchItemTextField1.getText();
        ArrayList<Object> itemDetails = getItem(Long.parseLong(itemId));
        DefaultTableModel model = (DefaultTableModel)jTransactionTable1.getModel();
        //row, id, name, price, quantity, discount, total price
        //model.addRow(new Object[]{row, itemDetails.get(0),itemDetails.get(1),itemDetails.get(2),quantity,0,10.0}); 
        //row++;
        
       
        int rowCount = model.getRowCount();
        int existingProductRowIndex = -1;
        row = rowCount+1;

        for (int i = 0; i < rowCount; ++i) {
            if (model.getValueAt(i, 1) != null && model.getValueAt(i, 1).equals(itemDetails.get(0))) {
                existingProductRowIndex = i;
                break;
            }
        }
        

        if (existingProductRowIndex > -1) {
            int originalQuantity = Integer.parseInt(model.getValueAt(existingProductRowIndex, 4).toString());
            double itemPrice = Double.parseDouble(model.getValueAt(existingProductRowIndex, 3).toString());
            model.setValueAt((originalQuantity+1), existingProductRowIndex, 4);
            quantity = originalQuantity+1;
            double discountAmt = checkBulkDiscountAmount(Long.parseLong(itemId), quantity);
            double aBDiscount = checkItemAItemBDiscount((Long)itemDetails.get(0), cart);
            aBDiscount /=100;
            aBDiscount *= itemPrice;
            double initialTotal = Double.parseDouble(model.getValueAt(existingProductRowIndex, 6).toString());
            double updTotal = (100-discountAmt)/100*itemPrice*(originalQuantity+1) - aBDiscount;
            model.setValueAt(((discountAmt)/100*itemPrice*(originalQuantity+1)+aBDiscount), existingProductRowIndex, 5);
            model.setValueAt(updTotal, existingProductRowIndex, 6);
            computeIncreaseInQty(updTotal, initialTotal);
            /*grandTotal += (updTotal-initialTotal);
            tax += (updTotal-initialTotal)*taxRate;
            double itemTax = (updTotal-initialTotal)*taxRate;
            grandTotal += itemTax;
            jTaxTextField3.setText(df.format(tax));
            jGrandTotalTextField3.setText(df.format(grandTotal));*/
        } else {
            double price = (Double)itemDetails.get(2);
            double discountAmt = checkBulkDiscountAmount(Long.parseLong(itemId), quantity);
            double aBDiscount = checkItemAItemBDiscount((Long)itemDetails.get(0), cart);
            discountAmt /= 100;
            aBDiscount /=100;
            double totalPrice = quantity*price;
            double disc = totalPrice*discountAmt + totalPrice*aBDiscount;
            totalPrice -= disc;
            model.addRow(new Object[]{row, itemDetails.get(0),itemDetails.get(1),itemDetails.get(2),quantity,disc,totalPrice});
            cart.add((Long)itemDetails.get(0));
            grandTotal /= (1+taxRate);
            grandTotal += totalPrice;
            tax = grandTotal*taxRate;
            grandTotal *= (1+taxRate);
            jTaxTextField3.setText(df.format(tax));
            jGrandTotalTextField3.setText(df.format(grandTotal));
            subtotal.setText(df.format(grandTotal/1.07));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSearchItemTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchItemTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchItemTextField1ActionPerformed

    private void jTransactionTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTransactionTable1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTransactionTable1KeyTyped

    private void jTransactionTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTransactionTable1KeyPressed
      DefaultTableModel model = (DefaultTableModel)jTransactionTable1.getModel();
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
           int updRow = jTransactionTable1.getSelectedRow();
           int updCol = jTransactionTable1.getSelectedColumn();
           int updQty = (Integer)jTransactionTable1.getValueAt(updRow, updCol);
           double updPrice = (Double)model.getValueAt(updRow, 3);
           double discountAmt = checkBulkDiscountAmount((Long)(model.getValueAt(updRow, 1)), updQty);
           discountAmt /= 100;
           double updTotal = updPrice*updQty;
           double discountAmtForBulk = updTotal * discountAmt;
           updTotal *= (1-discountAmt);
           double oldTotal = (Double)model.getValueAt(updRow, 6);
           model.setValueAt(updQty, updRow, updCol);
           model.setValueAt(discountAmtForBulk, updRow, 5);
           model.setValueAt(updTotal, updRow, 6);
           computeIncreaseInQty(updTotal, oldTotal);
           /*grandTotal /= (1-membershipDiscount);
           grandTotal /= (1+taxRate);
           grandTotal += (updTotal-oldTotal);
           discAmt = grandTotal*membershipDiscount;
           grandTotal *= (1-membershipDiscount);
           tax = grandTotal*taxRate;
           grandTotal *= (1+taxRate);
           discountField.setText(df.format(discAmt));
           jTaxTextField3.setText(df.format(tax));
           jGrandTotalTextField3.setText(df.format(grandTotal));
           */
       }
    }//GEN-LAST:event_jTransactionTable1KeyPressed

    private void jTransactionTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTransactionTable1KeyReleased

    }//GEN-LAST:event_jTransactionTable1KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTransactionTable1.getModel();
        int[] selectedRows = jTransactionTable1.getSelectedRows();
        if (selectedRows.length > 0) {
            for (int i = selectedRows.length - 1; i >= 0; i--) {
                double oldTotal = (Double)model.getValueAt(selectedRows[i], 6);
                Long deleteItemId = (Long)model.getValueAt(selectedRows[i], 1);
                cart.remove(deleteItemId);
                model.removeRow(selectedRows[i]);
                for(int j=i; j<model.getRowCount(); j++) {
                    while((int)model.getValueAt(j, 0)!=1)
                    model.setValueAt(((int)model.getValueAt(j, 0)-1), j, 0);
                }
                grandTotal /= (1+taxRate);
                grandTotal /= (1-membershipDiscount);
                grandTotal -= oldTotal;
                discAmt = (grandTotal*membershipDiscount);
                grandTotal *= (1-membershipDiscount);
                tax = grandTotal*taxRate;
                grandTotal *= (1+taxRate);
                discountField.setText(df.format(discAmt));
                jTaxTextField3.setText(df.format(tax));
                jGrandTotalTextField3.setText(df.format(grandTotal));
                subtotal.setText(df.format(grandTotal/1.07));
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String custId = jTextField4.getText();
            customerId = Long.parseLong(custId);
            double discountRate = overallMembershipDiscount(customerId);
            discountRate /= 100;
            membershipDiscount = discountRate;
            grandTotal /= (1+taxRate);
            discAmt = grandTotal*discountRate;
            grandTotal *= (1-discountRate);
            tax =grandTotal*taxRate;
            grandTotal *= (1+taxRate);
            discountField.setText(df.format(discAmt));
            jTaxTextField3.setText(df.format(tax));
            jGrandTotalTextField3.setText(df.format(grandTotal));
            subtotal.setText(df.format(grandTotal/1.07));
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       collateTransactionDetails();   
       PaymentUI newPayment =new PaymentUI();
       newPayment.setGrandTotalLabel(grandTotal);
       newPayment.setTransactionId(transactionID);
       newPayment.setVisible(true);
       newPayment.setExtendedState(JFrame.MAXIMIZED_BOTH);
       this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
   
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                NewTransaction newTransaction = new NewTransaction();
                newTransaction.setExtendedState(JFrame.MAXIMIZED_BOTH);
                newTransaction.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLab;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jGrandTotalTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jMembershipButton3;
    private javax.swing.JButton jNewTransactionButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JButton jProductsButton5;
    private javax.swing.JButton jPromotionsButton4;
    private javax.swing.JButton jRetrieveTransactionButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchItemTextField1;
    private javax.swing.JTextField jTaxTextField3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable jTransactionTable1;
    private javax.swing.JTextField subtotal;
    private javax.swing.JLabel timeLab;
    // End of variables declaration//GEN-END:variables

    private static ArrayList getItem(java.lang.Long itemId) {
        ws.client.managePOS.ManagePOSBeanService service = new ws.client.managePOS.ManagePOSBeanService();
        ws.client.managePOS.ManagePOSBean port = service.getManagePOSBeanPort();
        return (ArrayList)port.getItemDetails(itemId);
    }
    
     private static double checkBulkDiscountAmount(java.lang.Long itemId, java.lang.Integer itemQty) {
        ws.client.managePOS.ManagePOSBeanService service = new ws.client.managePOS.ManagePOSBeanService();
        ws.client.managePOS.ManagePOSBean port = service.getManagePOSBeanPort();
        return port.checkBulkDiscountAmount(itemId, itemQty);
    }
     
     private static double overallMembershipDiscount(java.lang.Long customerId) {
        ws.client.managePOS.ManagePOSBeanService service = new ws.client.managePOS.ManagePOSBeanService();
        ws.client.managePOS.ManagePOSBean port = service.getManagePOSBeanPort();
        return port.overallMembershipDiscount(customerId);
    }
     
     private static double checkItemAItemBDiscount(java.lang.Long itemId, java.util.ArrayList cart) {
        ws.client.managePOS.ManagePOSBeanService service = new ws.client.managePOS.ManagePOSBeanService();
        ws.client.managePOS.ManagePOSBean port = service.getManagePOSBeanPort();
        return port.checkItemAItemBDiscount(itemId, cart);
    }
     
     private static Long saveTransaction(java.util.ArrayList iTid, java.util.ArrayList iQty, java.util.ArrayList idiscAmt, java.util.ArrayList idiscP,java.util.ArrayList iTPrice, java.util.ArrayList transactionDetails) {
        ws.client.managePOS.ManagePOSBeanService service = new ws.client.managePOS.ManagePOSBeanService();
        ws.client.managePOS.ManagePOSBean port = service.getManagePOSBeanPort();
        return port.saveTransaction(iTid, iQty, idiscAmt, idiscP, iTPrice, transactionDetails);
    }
     
     private void computeIncreaseInQty(double updTotal, double oldTotal) {
           grandTotal /= (1-membershipDiscount);
           grandTotal /= (1+taxRate);
           grandTotal += (updTotal-oldTotal);
           discAmt = grandTotal*membershipDiscount;
           grandTotal *= (1-membershipDiscount);
           tax = grandTotal*taxRate;
           grandTotal *= (1+taxRate);
           discountField.setText(df.format(discAmt));
           jTaxTextField3.setText(df.format(tax));
           jGrandTotalTextField3.setText(df.format(grandTotal));
           subtotal.setText(df.format(grandTotal/1.07));
     }
     
     private void collateTransactionDetails(){
         //store each column into a arrayList ------discount% == 100(discount/total+discount)
         //store subtotal, total discount amount, total discount percentage, taxes and grandtotal
         //Store customerId
         //Store all of the above into a list and send to managePOS
         //managePOS create a transaction without payment details.
         /*
         ItemDetaillist looks like
         itemId -L, itemQty-L, discountAmt-L, discountPercent-L, itemTotalPrice-L, 
         TranactionDetailsList
         subTotal, totalDiscountAmount, totalDiscount%, taxes, grandTotal, customerId, currentTimeStamp
         */
        
         
        ArrayList iTid = new ArrayList();
        ArrayList iQty = new ArrayList();
        ArrayList idiscAmt = new ArrayList();
        ArrayList idiscP = new ArrayList();
        ArrayList iTPrice = new ArrayList();
        ArrayList transactionDetails = new ArrayList();
        System.out.println("test1");
        DefaultTableModel model = (DefaultTableModel)jTransactionTable1.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; ++i) {
            System.out.println("test2");
            iTid.add(model.getValueAt(i, 1)); //add item Ids from each row
            iQty.add(model.getValueAt(i, 4)); //add item qty from each row
            idiscAmt.add(model.getValueAt(i, 5)); //add discounr amount from each row
            iTPrice.add(model.getValueAt(i, 6)); //add total price from each row
            double tP = (Double)model.getValueAt(i, 6);
            double dA = (Double)model.getValueAt(i, 5);
            double dP = dA/(tP+dA);
            idiscP.add(dP); //add discount % from each row
            }
        System.out.println("test3");
        transactionDetails.add((grandTotal/1.07));
        transactionDetails.add(membershipDiscount*(grandTotal/(1+taxRate)));
        transactionDetails.add(membershipDiscount);
        transactionDetails.add(tax);
        transactionDetails.add(grandTotal);
        transactionDetails.add(customerId);
        String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new Date());
        transactionDetails.add(timeStamp);
        System.out.println("test4");
        transactionID = saveTransaction(iTid, iQty, idiscAmt, idiscP, iTPrice, transactionDetails);
        System.out.println("test5");
        //subtotal, totalDiscountAmt, totalDiscountPercentage, tax, grandtotal, customerId, timestamp
        System.out.println("test6");
        }    
}