/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intrasyspos;

import java.text.DecimalFormat;
import javax.swing.JFrame;



/**
 *
 * @author ashiq
 */
public class PaymentUI extends javax.swing.JFrame {

    public Long transactionID;
    public String paymentMethod;
    public double grandTotal;
    /**
     * Creates new form PaymentUI
     */
    DecimalFormat df = new DecimalFormat("0.00");
    public PaymentUI() {
        initComponents();
    }
    
    public void setGrandTotalLabel(double grandT){
        grandTotal = grandT;
        jLabel4.setText(df.format(grandT));
    }
    
    public void setTransactionId(Long tId) {
        transactionID = tId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jNewTransactionButton1 = new javax.swing.JButton();
        jRetrieveTransactionButton2 = new javax.swing.JButton();
        jMembershipButton3 = new javax.swing.JButton();
        jPromotionsButton4 = new javax.swing.JButton();
        jProductsButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cashButton = new javax.swing.JToggleButton();
        creditCardButton = new javax.swing.JToggleButton();
        amount = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amountDisplay = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jOptionPane2 = new javax.swing.JOptionPane();
        success = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jNewTransactionButton1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jNewTransactionButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cart.png"))); // NOI18N
        jNewTransactionButton1.setText("New Transaction");
        jNewTransactionButton1.setMinimumSize(new java.awt.Dimension(100, 100));
        jNewTransactionButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jNewTransactionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewTransactionButton1ActionPerformed(evt);
            }
        });

        jRetrieveTransactionButton2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jRetrieveTransactionButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/oldtransaction.png"))); // NOI18N
        jRetrieveTransactionButton2.setText("Retrieve Transaction");
        jRetrieveTransactionButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jRetrieveTransactionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetrieveTransactionButton2ActionPerformed(evt);
            }
        });

        jMembershipButton3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jMembershipButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Member.png"))); // NOI18N
        jMembershipButton3.setText("Membership");

        jPromotionsButton4.setBackground(new java.awt.Color(0, 0, 0));
        jPromotionsButton4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jPromotionsButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/promotions.png"))); // NOI18N
        jPromotionsButton4.setText("View Promotions");
        jPromotionsButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPromotionsButton4ActionPerformed(evt);
            }
        });

        jProductsButton5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jProductsButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/products.png"))); // NOI18N
        jProductsButton5.setText("View Products");
        jProductsButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductsButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings.png"))); // NOI18N
        jButton2.setText("Settings");
        jButton2.setMargin(new java.awt.Insets(2, -30, 2, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRetrieveTransactionButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNewTransactionButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMembershipButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPromotionsButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProductsButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNewTransactionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRetrieveTransactionButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jMembershipButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPromotionsButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProductsButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cashButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cashButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cash.png"))); // NOI18N
        cashButton.setText("Cash");
        cashButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashButtonMouseClicked(evt);
            }
        });
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });

        creditCardButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        creditCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/card.png"))); // NOI18N
        creditCardButton.setText("Credit Card");
        creditCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardButtonActionPerformed(evt);
            }
        });

        amount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        amount.setMinimumSize(new java.awt.Dimension(400, 50));
        amount.setPreferredSize(new java.awt.Dimension(400, 50));

        payButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setText("Grand Total: ");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setText("Amount Paid:");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel3.setText("Balance:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("jLabel4");

        amountDisplay.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        amountDisplay.setText("  ");

        balance.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        balance.setText("  ");

        success.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        success.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(creditCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(amountDisplay))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(balance))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(payButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton))
                .addGap(39, 39, 39)
                .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountDisplay))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(balance))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewTransactionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewTransactionButton1ActionPerformed
        NewTransaction newTransaction =new NewTransaction();
        newTransaction.setVisible(true);
        newTransaction.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
    }//GEN-LAST:event_jNewTransactionButton1ActionPerformed

    private void jRetrieveTransactionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetrieveTransactionButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRetrieveTransactionButton2ActionPerformed

    private void jPromotionsButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPromotionsButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPromotionsButton4ActionPerformed

    private void jProductsButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductsButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProductsButton5ActionPerformed

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        creditCardButton.setSelected(Boolean.FALSE);
        paymentMethod = "Cash";
        setPaymentDetails(paymentMethod, transactionID);
    }//GEN-LAST:event_cashButtonActionPerformed

    private void creditCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardButtonActionPerformed
        cashButton.setSelected(Boolean.FALSE);
        paymentMethod = "Credit Card";
        setPaymentDetails(paymentMethod, transactionID);
    }//GEN-LAST:event_creditCardButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        String amountPaid = amount.getText();
        double amountP = Double.parseDouble(amountPaid);
        double balanceAmt = amountP - grandTotal;
        amountDisplay.setText(amountPaid);
        balance.setText(df.format(balanceAmt));
        success.setText("Payment Successful");
    }//GEN-LAST:event_payButtonActionPerformed

    private void cashButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashButtonMouseClicked
        
    }//GEN-LAST:event_cashButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel amountDisplay;
    private javax.swing.JLabel balance;
    private javax.swing.JToggleButton cashButton;
    private javax.swing.JToggleButton creditCardButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jMembershipButton3;
    private javax.swing.JButton jNewTransactionButton1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jProductsButton5;
    private javax.swing.JButton jPromotionsButton4;
    private javax.swing.JButton jRetrieveTransactionButton2;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables

private static void setPaymentDetails(java.lang.String paymentMethod, java.lang.Long transactionID) {
        ws.client.managePOS.ManagePOSBeanService service = new ws.client.managePOS.ManagePOSBeanService();
        ws.client.managePOS.ManagePOSBean port = service.getManagePOSBeanPort();
        port.setPaymentDetails(paymentMethod, transactionID);
    }
     


}
